import type { VocabularyItem, VocabularySource } from '../types';
import data from './imported.json';

/**
 * Entries generated by `npm run import` (scripts/import-vocabulary.mjs) live in
 * imported.json; this wrapper only gives them their types. The JSON array is far
 * too large for TypeScript to type-check as an object literal, so the structure
 * is validated at runtime instead (validateDataset in ../index.ts, run by the tests).
 */
export const importedSources = data.sources as VocabularySource[];
export const importedVocabulary = data.items as unknown as VocabularyItem[];
